// Code generated by hertz generator.

package main

import (
	"flag"
	"hertz-demo/common/config"
	"hertz-demo/common/hertz"
	_ "hertz-demo/microservice/server1/docs"
	"hertz-demo/microservice/server1/g"
)

var (
	configFile = flag.String("f", "microservice/server1/etc/nacos.yaml", "the config file")
)

// @title HertzTest
// @version 1.0
// @description This is a demo using Hertz.

// @contact.name hertz-contrib
// @contact.url https://github.com/hertz-contrib

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8888
// @BasePath /
// @schemes http
func main() {
	flag.Parse()
	nacosConf := config.MustLoad(*configFile, g.Config)
	h := hertz.MustNewServer(nacosConf, &g.Config.Server)
	g.HertzClient = hertz.MustNewClient(nacosConf)
	register(h)
	g.InitServiceContext()
	h.Spin()
}
