// Code generated by hertz generator.

package main

import (
	"flag"
	"hertz-demo/common/config"
	"hertz-demo/common/hertz"
	"hertz-demo/microservice/server2/g"
)

// hertz-swagger middleware
// swagger embed files

var (
	configFile = flag.String("f", "microservice/server2/etc/nacos.yaml", "the config file")
)

func main() {
	flag.Parse()
	nacosConf := config.MustLoad(*configFile, g.Config)
	h := hertz.MustNewServer(nacosConf, &g.Config.Server)
	g.HertzClient = hertz.MustNewClient(nacosConf)
	g.InitServiceContext()

	register(h)

	h.Spin()
}
