// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	hello_example "hertz-demo/microservice/server1/biz/router/hello/example"
	hello2_example "hertz-demo/microservice/server1/biz/router/hello2/example"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	hello2_example.Register(r)

	hello_example.Register(r)
}
