// Code generated by hertz generator.

package example

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"hertz-demo/common/model"
	"hertz-demo/microservice/server1/g"

	"github.com/cloudwego/hertz/pkg/app"
	example "hertz-demo/microservice/server1/biz/model/hello/example"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.HelloReq
	var resp = &model.Response[example.HelloResp]{C: c}
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}
	hlog.Info("hahahahahha")

	data := new(example.HelloResp)
	chartModel, err := g.HelmChartDao.GetByID(44)
	if err != nil {
		hlog.Error(err)
	}
	data.RespBody = "hello zze, this chart name's " + chartModel.Name
	resp.JsonOk("ok", data)
}
