// Code generated by hertz generator.

package example

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"hertz-demo/common/model"

	"github.com/cloudwego/hertz/pkg/app"
	example "hertz-demo/microservice/server1/biz/model/hello2/example"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(example.HelloResp)

	c.JSON(200, resp)
}

// TestPost .
// @router /test-post [POST]
func TestPost(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.TestPostReq
	var resp = &model.Response[example.TestPostResp]{C: c}
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	hlog.Info(req.Name)

	data := new(example.TestPostResp)
	data.Msg = "hello " + req.Name

	resp.JsonOk("ok", data)
}
